export { default as GithubIcon } from "./github.svg";
export { default as MailIcon } from "./mail.svg";
export { default as TwitterIcon } from "./twitter.svg";
export { default as YoutubeIcon } from "./youtube.svg";
export { default as SlackIcon } from "./slack.svg";
export { default as FacebookIcon } from "./facebook.svg";
export { default as LinkedInIcon } from "./linkedin.svg"
export { default as GoogleMeetIcon } from "./meet.svg";
export { default as InstagramIcon } from "./instagram.svg"